add missing widgets variable to class
ERROR in apps/dashboard/src/app/widgets/widgets.component.ts:61:10

 - error TS2551: Property 'widgets' does not exist on type 'WidgetsComponent'.